### ISSUE TITLE
more graceful error handling

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/wplibcalhours#16]
currently, if an error occurs whilst retrieving/processing data from the LibCal API, the rendered output is blank.
change this to always show a table with the given number of calendar dates, but display "n/a" in the hours column.

**Comment by stopfstedt** [comment]
@mizejewski @tmcdev , please let me know if you have any other/additional ideas re: graceful error handling. thanks!

**Comment by mizejewski** [comment]
For example, this might happen if the LibGuides server went down? I'm assuming an error retrieving/processing data would rarely happen, so "n/a" is probably a good solution (and certainly better than not loading anything and just showing a black area.)

**Comment by stopfstedt** [comment]
@mizejewski that's exactly the scenario i had in mind. Thanks for the confirmation, i'll proceed as agreed upon then.
On a related note - all errors are written to the server log, but i don't know if we have access to those in our hosting environment (i'll follow up n this and track it in Trello since it's not really a code issue)
