### ISSUE TITLE
Clarify Usage section in README.md

### ISSUE THREAD

**Issue by mizejewski** [ucsf-ckm/wplibcalhours#22]
It would help to add examples of what the shortcode should look like with different possible combinations of information. 

For example, the basic is 
`[wplibcalhours location="Parnassus Library"]` 

We're currently using the pattern 
`[wplibcalhours location="Parnassus Library" start_date=false]` 

Do I need to also add `num_weeks`? If so, what does that shortcode syntax look like?

**Comment by stopfstedt** [comment]
i removed the `start_date` option, see #18, please feel free to remove it from the embedded short codes.

`num_weeks` will default to three weeks, no need to specify it unless you want a shorter range.

all available options are documented here: https://github.com/ucsf-ckm/wplibcalhours#usage

**Comment by stopfstedt** [comment]
oh right, will add examples to the usage section. good point.

**Comment by stopfstedt** [comment]
closed via #23.
