### ISSUE TITLE
Include a LibCal screenshot in the README.md

### ISSUE THREAD

**Issue by mizejewski** [ucsf-ckm/wplibcalhours#6]
LibCal is convoluted and unintuitive, so it would be helpful to include the path and an illustrative screenshot, so it's clear where to generate the API endpoint.

**LibCal** > **Amin** > **Hours** > **Widgets tab** > **Weekly Data tab** > **show X weeks** > format: **JSON**

<img width="831" alt="generate-from-libcal" src="https://cloud.githubusercontent.com/assets/974442/24482492/6a247c24-14a6-11e7-972d-f53d847a00b7.png">

**Comment by mizejewski** [comment]
When generating the embed code what goes is the **# Weeks** to Show field? Does is have to be 3, or should it stay at the default (1) because your code overrides that bit?

**Comment by stopfstedt** [comment]
i'd set it to five.

you'll need two more weeks than the max number of weeks displayed, which is hardwired to three.

**Comment by stopfstedt** [comment]
https://github.com/ucsf-ckm/wplibcalhours/wiki/How-to-get-the-LibCal-API-Endpoint
